# -*- coding: utf-8 -*-
"""rotten_tomatoes_top_100.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DgFmINLcVBYqd1nbGOH7JeQkdcK_Uk4r
"""

from bs4 import BeautifulSoup

import requests
import pandas as pd

##Request page source from url



url="https://editorial.rottentomatoes.com/guide/best-movies-21st-century/"

page =requests.get(url)
page

page.content

soup=BeautifulSoup(page.content,"html.parser")
print(soup.prettify())

scraped_movies=soup.find_all('div',class_='article_movie_title')
scraped_movies

movies=[]
ratings=[]
for movie in scraped_movies:
  movie=movie.get_text()
  moviee=movie.split('(')[0].strip()
  movies.append(moviee)
  rating=movie.split(' ')[-2].strip('\n')
  ratings.append(rating)

print(movies)

print(ratings)

data=pd.DataFrame()
data['Movies']=movies
data['Ratings']=ratings

data.sort_values(by='Ratings', ascending=False)

data.to_csv('rotten_tomatoes_top_100.csv',index=False)